// Generated by CoffeeScript 1.6.2
(function() {
  window.InfoBar = (function() {
    function InfoBar($info_bar, room) {
      this.$info_bar = $info_bar;
      this.room = room;
    }

    InfoBar.prototype.report = function(message) {
      if (this.$info_bar.find('div').length > 4) {
        this.$info_bar.find('div').first().remove();
      }
      return this.$info_bar.append("<div>" + (this.current_time()) + " : " + message + "</div>");
    };

    InfoBar.prototype.current_time = function() {
      var d;

      d = new Date();
      return "" + (d.getHours()) + ":" + (d.getMinutes()) + ":" + (d.getSeconds());
    };

    return InfoBar;

  })();

}).call(this);
