// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    return $('#go_button').on('click', function() {
      var room_id, user_id;

      room_id = $('#room_id').val();
      user_id = $('#user_id').val();
      if (room_id && user_id) {
        return window.room = new Room('ws:localhost:9090', room_id, user_id);
      }
    });
  });

}).call(this);
